# PersistentVolumeClaim for storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# Job for initializing storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-storage
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: alpine/git
        command: ["/bin/sh", "-c"]
        args:
        - |
          git clone https://github.com/jayzaa/jay-disk /mnt/storage &&
          cp -r /mnt/storage/full/disk/* /mnt/data
        volumeMounts:
        - name: app-storage-volume
          mountPath: /mnt/data
      restartPolicy: OnFailure
      volumes:
      - name: app-storage-volume
        persistentVolumeClaim:
          claimName: app-storage-pvc
