apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: amz-oss-disk
  name: amz-oss-disk
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: amz-pvc
    namespace: appcenter
  csi:
    driver: ossplugin.csi.alibabacloud.com
    nodePublishSecretRef:
      name: alyn-oss-appcenter-ubuntu
      namespace: appcenter
    volumeAttributes:
      bucket: alyn-oss-appcenter-ubuntu
      otherOpts: ''
      path: /data
      url: oss-ap-southeast-1-internal.aliyuncs.com
    volumeHandle: amz-oss-disk
  storageClassName: oss
  volumeMode: Filesystem
