apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
  annotations:
    deploymentTimestamp: "{{ now }}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: oss
  resources:
    requests:
      storage: 40Gi