apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  labels:
    app: ubuntu
  annotations:
    deploymentTimestamp: "{{ now }}"
spec:
  selector:
    app: ubuntu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer