apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-os
  labels:
    app: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80
        - containerPort: 22
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: ubuntu-storage
          mountPath: /data
      volumes:
      - name: ubuntu-storage
        persistentVolumeClaim:
          claimName: ubuntu-pvc

