apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-os
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      initContainers:
      - name: install-nginx
        image: ubuntu:24.04
          command:
            - bash
            - -c
            - |
              apt-get update && \
              apt-get install -y curl wget htop nginx openssh-server && \
              echo 'daemon off;' >> /etc/nginx/nginx.conf && \
              mkdir /var/run/sshd && \
              echo 'root:root' | chpasswd && \
              sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
              sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config && \
              cp -r /etc/nginx /nginx-config && \
              cp -r /etc/ssh /ssh-config    
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /nginx-config
            name: nginx-config
          - mountPath: /ssh-config
            name: ssh-config
          - name: ubuntu-storage
            mountPath: /data
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command:
          - bash
          - -c
          - |
            cp -r /nginx-config /etc/nginx && \
            cp -r /ssh-config /etc/ssh && \
            service ssh start && \
            nginx
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 22
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: ubuntu-storage
          mountPath: /data
        - mountPath: /nginx-config
          name: nginx-config
        - mountPath: /ssh-config
          name: ssh-config
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "cp -r /nginx-config /etc/nginx && nginx"]
      volumes:
      - name: ubuntu-storage
        persistentVolumeClaim:
          claimName: ubuntu-pvc
      - name: nginx-config
        emptyDir: {}
      - name: ssh-config
        emptyDir: {}

