apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-os
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      initContainers:
      - name: install-nginx
        image: ubuntu:24.04
        command:
          - bash
          - -c
          - |
            apt-get update && \
            apt-get install -y curl wget htop nginx openssh-server
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /nginx-config
            name: nginx-config
          - mountPath: /ssh-config
            name: ssh-config
          - name: ubuntu-storage
            mountPath: /data
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 22
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: ubuntu-storage
          mountPath: /data
        - mountPath: /nginx-config
          name: nginx-config
        - mountPath: /ssh-config
          name: ssh-config
      volumes:
      - name: ubuntu-storage
        persistentVolumeClaim:
          claimName: ubuntu-pvc
      - name: nginx-config
        emptyDir: {}
      - name: ssh-config
        emptyDir: {}

