apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-oss
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  labels:
    app: ubuntu
spec:
  selector:
    app: ubuntu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-os
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      initContainers:
      - name: install-nginx
        image: ubuntu:24.04
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y nginx && cp -r /etc/nginx /data/nginx && cp -r /var/www/html /data/html && cp -r /usr/share/nginx/html /data/html
        volumeMounts:
        - name: ubuntu-storage
          mountPath: /data
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80
        - containerPort: 22
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: ubuntu-storage
          mountPath: /data
      volumes:
      - name: ubuntu-storage
        persistentVolumeClaim:
          claimName: ubuntu-pvc

