apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      initContainers:
      - name: init-ubuntu
        image: ubuntu:latest
        command:
        - sh
        - -c
        - |
          apt-get update && \
          apt-get install -y curl apache2 htop && \
          cp /usr/sbin/apache2ctl /workdir/apache2ctl && \
          chmod +x /workdir/apache2ctl
        volumeMounts:
        - mountPath: /workdir
          name: workdir
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/workdir/apache2ctl"]
        args: ["-D", "FOREGROUND"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /workdir
          name: workdir
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: workdir
        emptyDir: {}
