apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: appcenter
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayByCLCU
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-scheduler: rr
  labels:
    app: guestbook
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 3000
  sessionAffinity: None
  type: LoadBalancer