apiVersion: apps/v1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    path: ''
    targetRevision: HEAD
    kustomize:
      kustomizeVersion: v3.5.4
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-ingress-controller
          labels:
            app: nginx-ingress
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx-ingress
          template:
            metadata:
              labels:
                app: nginx-ingress
            spec:
              containers:
              - name: nginx-ingress-controller
                image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
                ports:
                - containerPort: 80
                - containerPort: 443
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"

      - apiVersion: v1
        kind: Service
        metadata:
          name: nginx-ingress-controller
        spec:
          selector:
            app: nginx-ingress
          ports:
          - protocol: TCP
            port: 80
            targetPort: 80
          - protocol: TCP
            port: 443
            targetPort: 443
          type: LoadBalancer
