apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-postgresql
  namespace: gitlab
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:11
        ports:
        - containerPort: 5432
