apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    path: ''
    targetRevision: HEAD
    kustomize:
      kustomizeVersion: v3.5.4
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-ingress-controller
          labels:
            app: nginx-ingress
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx-ingress
          template:
            metadata:
              labels:
                app: nginx-ingress
            spec:
              containers:
              - name: nginx-ingress-controller
                image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
                ports:
                - containerPort: 80
                - containerPort: 443
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "500m"
                    memory: "512Mi"

      - apiVersion: v1
        kind: Service
        metadata:
          name: nginx-ingress-controller
        spec:
          selector:
            app: nginx-ingress
          ports:
          - protocol: TCP
            port: 80
            targetPort: 80
          - protocol: TCP
            port: 443
            targetPort: 443
          type: LoadBalancer

      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: php-fpm-deployment
          labels:
            app: php-fpm
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: php-fpm
          template:
            metadata:
              labels:
                app: php-fpm
            spec:
              containers:
              - name: php-fpm
                image: php:5.6-fpm
                ports:
                - containerPort: 9000
                volumeMounts:
                - name: php-code
                  mountPath: /var/www/html
                resources:
                  requests:
                    cpu: "1"
                    memory: "512Mi"
                  limits:
                    cpu: "1"
                    memory: "512Mi"
              volumes:
              - name: php-code
                configMap:
                  name: php-code

      - apiVersion: v1
        kind: Service
        metadata:
          name: php-fpm-service
        spec:
          selector:
            app: php-fpm
          ports:
          - protocol: TCP
            port: 9000
            targetPort: 9000

      - apiVersion: autoscaling/v2beta2
        kind: HorizontalPodAutoscaler
        metadata:
          name: php-fpm-hpa
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: php-fpm-deployment
          minReplicas: 1
          maxReplicas: 8
          metrics:
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 50
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 50

      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: php-fpm-ingress
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_pass_request_headers on;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
        spec:
          rules:
          - host: yourdomain.com
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: php-fpm-service
                    port:
                      number: 9000

      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: php-code
        data:
          index.php: |
            <?php phpinfo(); ?>