apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-jay
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Use the desired Nginx image
        ports:
        - containerPort: 80
