apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jay-lab-3
  name: nginx-service
  namespace: jay-lab-3
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer

