# PHP-FPM Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:8.2-fpm
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: app-storage-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-storage-volume
        persistentVolumeClaim:
          claimName: app-storage-pvc